spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.232:3306/yanwei_mall_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: Yanweimall
    password: Yw2018
mybatis:
  mapper-locations: classpath:mapper/*.xml
