spring:
  application:
    name: eureka-server
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    service-url: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false